config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'tweets/last', to: 'tweets#last_tweets'
      get 'tweets/:date1/:date2', to: 'tweets#by_dates'
      post 'tweets/newtweet', to: 'tweets#create'
      post 'users/sign_in', to: 'devise/sessions#create'
    end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'tweets#index'
  resources 'tweets'
  post 'tweets/retweets/:id', to: 'tweets#retweets', as: 'retweets'
  post 'tweets/:tweet_id/likes', to: 'likes#like', as: 'like'
  post 'tweets/:tweet_id/dislikes', to: 'likes#dislike', as: 'dislike'
  post 'follows/:id', to: 'follows#to_follow', as: 'follow'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :content, presence: true
    belongs_to :user
    has_many :likes, dependent: :destroy
    # relación recursirva para hacer retweets
    has_many :retweets, class_name: "Tweet", foreign_key: "tweet_id", dependent: :destroy
    belongs_to :original_tweet, class_name: "Tweet", foreign_key: "tweet_id", optional: true

    # límites de registros a mostrar por página
    paginates_per 50
    
    scope :tweets_for_me, -> (user) { where(:user_id => user.followeds.pluck(:followed_id)) }

    def set_photo
        self.user.photo
    end

    def set_rt_count
        self.retweets.count
    end

    def set_user_name
        self.user.name
    end

    def set_likes_count
        self.likes.count
    end

    def set_origin_photo
        Tweet.find(self.tweet_id).user.photo
    end

    def set_origin_user
        Tweet.find(self.tweet_id).user.name
    end
    
    def set_origin_content
        Tweet.find(self.tweet_id).content
    end
    
    def set_origin_date
        Tweet.find(self.tweet_id).created_at
    end
    
end

app/controllers/api/v1/tweets_controller.rb
module Api
    module V1
        class TweetsController < V1Controller

            def by_dates
                # tweets = Tweet.find_by(created_at: params[:created_at])
                # # tweets = Tweet.where('DATE(created_at) = ?', params[:created_at])
                # tweets = Tweet.where('DATE(created_at) ? and ?', params[:created_at], params[:created_at])
                @date1 = params[:date1]
                @date2 = params[:date2]
                tweets = Tweet.where('DATE(created_at) > ? AND DATE(created_at) < ?', @date1, @date2)
                render json: tweets
            end

            def last_tweets
                @tweets = Tweet.last(50)
                last_tweets = @tweets.each do |tweet|
                    {
                        "id":  tweet.id,
                        "content": tweet.content,
                        "user_id": tweet.user_id,
                        "likes_count": Like.where(tweet_id: tweet.id).count,
                        "retweet_count": Tweet.where(tweet_id: tweet.id).count,
                        "retweeted_from": tweet.tweet_id
                    }
                end
                render json: last_tweets
            end

            def create
                @tweet = Tweet.create(content: [:content])
                render json: @tweet
            end
            
            
        end
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # solo si usuario está logeado puede acceder
  before_action :authenticate_user!, only: [ :retweets, :show ]
  
  def index
    if params[:q]
      # búsqueda parcial por el content del tweet
      @tweets = Tweet.where('content LIKE ?', "%#{params[:q]}%").order(created_at: :desc).page params[:page]
    elsif user_signed_in?
      @tweets = Tweet.tweets_for_me(current_user).or(current_user.tweets).order(created_at: :desc).page params[:page]
    else
      @tweets = Tweet.all.order(created_at: :desc).page params[:page]
      # @tweets = Tweet.eager_load(:user, :likes).order(created_at: :desc).page params[:page]
    end
    @tweet = Tweet.new
    @likes = Like.where(user: current_user).pluck(:tweet_id)
    # @users = User.where('id IS NOT ?', current_user.id).last(5) if user_signed_in? # Error en Heroku
    @users = User.where.not(id: current_user.id).last(5) if user_signed_in?

  end

  def create
    @users = User.all
    @tweets = Tweet.all.order(created_at: :desc).page params[:page]
    @likes = Like.where(user: current_user).pluck(:tweet_id)
    @tweet = Tweet.new(content: params[:tweet][:content])
    @tweet.user = current_user
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "¡Tweet creado con éxito!" }
      else
        format.html { render :index }
      end
    end 
  end
  
  def retweets
    @tweet = Tweet.find(params[:id])

    @retweet = Tweet.new
    @retweet.content = @tweet.content
    @retweet.user_id = current_user.id
    @retweet.tweet_id = @tweet.id
    @retweet.created_at = DateTime.now
    @retweet.updated_at = DateTime.now

    respond_to do |format|
      if @retweet.save
        format.html { redirect_to root_path, notice: "¡Haz hecho un RT éxito!" }
      else
        format.html { render :index }
      end
    end

  end
  
  def show
    @tweet = Tweet.find(params[:id])
    @tweet_likes = @tweet.likes
  end

end

app/helpers/api/v1/tweets_helper.rb
module Api::V1::TweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def hashtag(content)
        format_content = content.split(" ")
        tag = []
        format_content.each do |c|
            if c.start_with?("#")
                c = link_to c, controller: "tweets", q: c
            end
            tag << c
        end
        raw tag.join(" ")
    end
    
end

app/views/tweets/_users_to_follow.html.erb
<% current_user.you_follow.each do |user| %>
    <% if user.id != current_user.id %>
        <%= image_tag user.photo, class:"rounded-circle", style:"border: 2px solid black" %>
        <%= link_to follow_path(user.id), class:"btn btn-primary", method: :post do %>
            <%= "Seguir" %>
        <% end %>
    <% end %>
<% end %>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
    <div class= "container text-center pb-4">
        <h3>Estos usuarios también usan <strong>Twitter1.0</strong></h3>
        <hr>
        <%= render 'users_to_follow' %>
    </div>
<%end %>

<%= form_with(model: @tweet, local: true) do |f| %>
    <% if @tweet.errors.any? %>
        <div id = 'alert' class="alert alert-danger alert-dismissable pt-1">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h2 > oh! oh! :( no se pudo crear el tweet</h2>
            <ul>
                <% @tweet.errors.full_messages.each do |msg|%>
                    <% if msg == "Content can't be blank" %>
                        <li><%= "Debes ingresar un contenido." %></li>
                    <% else %>
                        <li><%= msg %></li>
                    <% end %>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if user_signed_in? %>
        <div class = 'form-group'>
            <%= f.label :content, "Ingresa tu tweet" %>
            <%= f.text_area :content, placeholder: "¿Que está pasando?", class: "form-control tweet-contain" %>
        </div>

        <div class = 'actions'>
            <%= f.submit "Twittear", class: "btn btn-success btn-tweetear" %>
        </div>
    <% end %>
<% end %>

<div class="row">
    <% @tweets.each do |t| %>
        <% if t.tweet_id == nil %>
            <div class="card col-12 m-3 bg-secondary tweet-container" >
                <div class="container text-left">
                    <!-- Imágen del usuario que hizo el tweet -->
                    <%= image_tag t.set_photo, class: "card-img-top pt-2 rounded-circle" %>
                    <!-- Nombre del usuario que hizo el tweet -->
                    <h6><%= t.set_user_name %> - Dice:</h6>
                </div>
                <div class="card-body bg-white">
                    <!-- Contenido del tweet -->
                    <p class="card-text"><%= hashtag(t.content) %></p>
                    <p class="mb-0">--</p>
                    <span><%= link_to distance_of_time_in_words(Time.now, t.created_at), t %></span>
                </div>
                <div class="text-center pt-2 pb-2">
                    <span>
                        <!-- Retweet -->
                        <%= link_to retweets_path(t.id), method: :post do %>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-repeat" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round" >
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M4 12v-3a3 3 0 0 1 3 -3h13m-3 -3l3 3l-3 3" />
                                <path d="M20 12v3a3 3 0 0 1 -3 3h-13m3 3l-3 -3l3 -3" />
                            </svg>
                        <% end %>
                    <span><span><%= t.set_rt_count %></span>
                    <% if @likes.include? t.id %>
                        <span>
                        <%= link_to dislike_path(t.id), method: :post do %>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-broken" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                            <path d="M12 7l-2 4l4 3l-2 4v3" />
                            </svg>
                        <% end %>
                        </span><span><%= t.set_likes_count %></span>
                    <% else %>
                        <span>
                            <!-- Likes -->
                            <%= link_to like_path(t.id), method: :post do %>
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                                </svg>
                            <% end %>
                        </span><span><%= t.set_likes_count %></span>
                    <% end %>
                </div>
            </div>
        <% else %>
            <div class="card col-12 m-3 bg-secondary tweet-container" >
                <div class="container text-left">
                    <!-- Imágen del usuario que hizo el tweet -->
                    <%= image_tag t.set_photo, class: "card-img-top pt-2 rounded-circle" %>
                    <!-- Nombre del usuario que hizo el tweet -->
                    <h6><%= t.set_user_name %> - Retweet:</h6>
                </div>
                <!-- Contenido del Rtweet -->
                <div class="card-body-rt">
                    <div class="card col-12 bg-info tweet-container" >
                        <%= image_tag t.set_origin_photo, class: "card-img-top rounded-circle2" %>
                        <h6><%= t.set_origin_user %> - Dijo:</h6>
                        <div class="card-body bg-white mb-3">
                            <p class="card-text"><%= t.set_origin_content %></p>
                            <p class="mb-0">--</p>
                            <%= link_to distance_of_time_in_words(Time.now, t.set_origin_date), ("tweets/#{t.tweet_id.to_s}") %>
                        </div>
                    </div>
                </div>
                <!-- Botones likes & retweet -->
                <div class="text-center pt-2 pb-2">
                <span class="pr-5"><%= link_to distance_of_time_in_words(Time.now, t.created_at), t %></span>
                    <!-- Retweet -->
                    <span>
                        <%= link_to retweets_path(t.id), method: :post do %>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-repeat" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round" >
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M4 12v-3a3 3 0 0 1 3 -3h13m-3 -3l3 3l-3 3" />
                                <path d="M20 12v3a3 3 0 0 1 -3 3h-13m3 3l-3 -3l3 -3" />
                            </svg>
                        <% end %>
                    <span><span><%= t.set_rt_count %></span>
                    <% if t.set_likes_count == 1 %>
                        <span>
                        <%= link_to dislike_path(t.id), method: :post do %>
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-broken" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                            <path d="M12 7l-2 4l4 3l-2 4v3" />
                            </svg>
                        <% end %>
                        </span><span><%= t.set_likes_count %></span>
                    <% else %>
                        <span>
                            <!-- Likes -->
                            <%= link_to like_path(t.id), method: :post do %>
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="30" height="30" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                                </svg>
                            <% end %>
                        </span><span><%= t.set_likes_count %></span>
                    <% end %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

<%= link_to_next_page @tweets, "Mostrar más ->", class: "btn btn-info" %>
<%= link_to_previous_page @tweets, "<- Anterior", class: "btn btn-info" %>

app/views/tweets/show.html.erb
<%= link_to '<- Volver', tweets_path, class: "btn btn-primary mb-3 mt-3 btn-tweetear" %>

<div class="card col-12 pb-3 bg-secondary tweet-container" >
    <div class="container text-left">
        <!-- Imágen del usuario que hizo el tweet -->
        <%= image_tag @tweet.set_photo, class: "card-img-top pt-2 rounded-circle" %>
        <!-- Nombre del usuario que hizo el tweet -->
        <h6><%= @tweet.set_user_name %> - Dice:</h6>
    </div>
    <div class="card-body bg-white">
        <!-- Contenido del tweet -->
        <p class="card-text"><%= @tweet.content %></p>
        <p class="mb-0">--</p>
        <span><%= @tweet.created_at.strftime("%d-%m-%Y %H:%M") %></span>
    </div>
</div><br><br>

<% if @tweet.set_likes_count == 0 %>
    <h2 class="alert alert-danger pt-1">oh! :( nadie le ha dado like a este tweet </h2>
    <% else %>
    <h2 class="alert alert-success pt-1">Estos usuarios le han dado like al tweet</h2>
<% end %>

<% @tweet_likes.each do |like| %>
    <div class="card col-12 pb-3 mt-3 bg-secondary tweet-container">
        <%= image_tag like.user.photo, class: "card-img-top pt-2 rounded-circle" %>
        <%= like.user.name %>
        <hr>
    </div>
<% end %>